# Generated by Django 2.0rc1 on 2017-11-25 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('streetname', models.CharField(max_length=50)),
                ('metatype', models.CharField(choices=[('human', 'Human'), ('ork', 'Ork'), ('troll', 'Troll'), ('elf', 'Elf'), ('dwarf', 'Dwarf')], max_length=20)),
                ('ethnos', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('de', 'de_DE'), ('en', 'en_GB')], max_length=5),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
