# Generated by Django 2.0rc1 on 2017-11-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171125_1703'),
        ('api', '0003_auto_20171125_1651'),
    ]

    operations = [
    ]
