# Generated by Django 2.0rc1 on 2017-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ethnos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
